
services:
  web:
    build: .
    ports:
      - "5050:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:mypassword@db:5432/flask_db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: flask_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
